version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    restart: always
    logging:
      options:
        max-size: "1g"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data/mongodb:/data/db